import Head from "next/head";
import styles from "../styles/Consumer.module.scss";

import Carousel from "react-multi-carousel";
import "react-multi-carousel/lib/styles.css";
import React, { useState, useEffect, useRef } from "react";
import AOS from "aos";
import "aos/dist/aos.css";
import Nav from "../components/Nav";
import Modal from "../components/Modal";
import Pagination from "../components/Pagination";

export default function Consumer() {
  const [showModal, setShowModal] = useState(false);
  const [width, setwidth] = useState("");
  const sliderRef = useRef(null);

  useEffect(() => {
    AOS.init({
      offset: 100,
    });

    if (typeof window !== "undefined") {
      let width_ =
        document.body.clientWidth ||
        window.innerHeight ||
        document.documentElement.clientHeigh;

      setwidth(width_);
    }
  }, []);

  const responsive = {
    superLargeDesktop: {
      breakpoint: { max: 4000, min: 3000 },
      items: 1,
    },
    desktop: {
      breakpoint: { max: 3000, min: 1024 },
      items: 1,
    },
    tablet: {
      breakpoint: { max: 1024, min: 464 },
      items: 1,
    },
    mobile: {
      breakpoint: { max: 464, min: 0 },
      items: 1,
    },
  };

  const data = [
    {
      id: 1,
      title: `Watch and enjoy\n fun, addicting and\n exhilarating videos`,
      subtext: `Are you bored or tired? Do not fret! Download Discover.App and enjoy lots of 
        entertainment to wash your boredom away. Just scroll through the unending
        fun gameplay & app preview videos. It is like TikTok and Twitch had a baby!`,
    },
    {
      id: 1,
      title: `Curate your own
      rankings and share
      with your friends `,
      subtext: `Let’s get creative and put our editor’s hats on. Rank your favorite apps, 
      games, content & creators while sharing your rankings with your friends. You 
      may be rewarded as your rankings go viral. It is a social experience!`,
    },
  ];

  const datam = [
    {
      id: 1,
      title: "Watch and enjoy fun, addicting and exhilarating videos",
      subtext:
        "Are you bored or tired? Do not fret! Download Discover.App and enjoy lots of entertainment to wash your boredom away. Just scroll through the unending fun gameplay & app preview videos. It is like TikTok and Twitch had a baby!",
    },
    {
      id: 1,
      title: "Curate your own rankings and share with your friends ",
      subtext:
        "Let’s get creative and put our editor’s hats on. Rank your favorite apps,  games, content & creators while sharing your rankings with your friends. You  may be rewarded as your rankings go viral. It is a social experience!",
    },
  ];

  const scroll = [
    {
      id: 1,
      title: `Curate your \n
        own top 10 \n
        rankings & \n
        share with\n
        your friends`,
    },
    {
      id: 1,
      title: `Earn for \n
        completing\n
        tasks for\n
        brands`,
    },
    {
      id: 3,
      title: `Scroll\n
        through \n
        interactive\n
        gameplay`,
    },
    {
      id: 1,
      title: `Download\n
        apps & games\n
        directly in\n
        your feed`,
    },
  ];

  const scrollm = [
    {
      id: 1,
      title: "Curate your own top 10 rankings & share with your friends",
    },
    {
      id: 1,
      title: `Earn for completing tasks for brands`,
    },
    {
      id: 3,
      title: `Scroll through  interactive gameplay`,
    },
    {
      id: 1,
      title: `Download apps & games directly in your feed`,
    },
  ];

  return (
    <div className={styles.container}>
      <Head>
        <title>Discover</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Nav
          onPress={() => {
            setShowModal(true);
          }}
        />

        <Carousel
          responsive={responsive}
          autoPlay={true}
          infinite={true}
          showArrows={false}
          showStatus={false}
          autoPlaySpeed={10000}
          showDots={false}
          swipeable={true}
          arrows={false}
          pauseOnHover={false}
        >
          {width <= 600
            ? datam.map((item, index) => {
                return (
                  <section key={index} className={styles.hero}>
                    <div className={styles.herocontent}>
                      <Pagination page={index + 1} sliderRef={sliderRef} />
                      <h1>{item.title}</h1>
                      <p>{item.subtext}</p>
                      <div className={styles.herobtn}>Sign Up</div>
                    </div>

                    <img className={styles.heroimg} src="cm1.png" alt="hero" />
                  </section>
                );
              })
            : data.map((item, index) => {
                return (
                  <section key={index} className={styles.hero}>
                    <div className={styles.herocontent}>
                      <Pagination page={index + 1} sliderRef={sliderRef} />
                      <h1>{item.title}</h1>
                      <p>{item.subtext}</p>
                      <div className={styles.herobtn}>Sign Up</div>
                    </div>

                    <img
                      className={styles.heroimg}
                      src="chero1.png"
                      alt="hero"
                    />
                  </section>
                );
              })}
        </Carousel>
      </main>

      <section className={styles.hero2}>
        <div className={styles.hero2content}>
          <h1>Start Discovering</h1>
          {width <= 600 ? (
            <p>
              Scroll through an interactive feed of apps <br />
              or games and start downloading directly from <br />
              the AppStore, PlayStore or Amazon Store
            </p>
          ) : (
            <p>
              Scroll through an interactive feed of apps or games and start
              downloading directly from <br />
              the AppStore, PlayStore or Amazon Store
            </p>
          )}
        </div>

        <div className={styles.scroll}>
          {width <= 600
            ? scrollm.map((item, index) => {
                return (
                  <div
                    style={{
                      backgroundImage: `url(opi${item.id}.png)`,
                    }}
                    key={index}
                    className={styles.scrollitem}
                  >
                    <h1>{item.title}</h1>

                    <img
                      src={`pill${index + 1}.png`}
                      alt="pill"
                      className={styles.pill}
                    />
                  </div>
                );
              })
            : scroll.map((item, index) => {
                return (
                  <div
                    style={{
                      backgroundImage: `url(opi${item.id}.png)`,
                    }}
                    key={index}
                    className={styles.scrollitem}
                  >
                    <h1>{item.title}</h1>

                    <img
                      src={`pill${index + 1}.png`}
                      alt="pill"
                      className={styles.pill}
                    />
                  </div>
                );
              })}
        </div>
      </section>

      <section className={styles.hero3}>
        <div className={styles.hero3content}>
          {width <= 600 ? (
            <h1>Explore new apps & games with ease</h1>
          ) : (
            <h1>
              Explore new <br />
              apps & games <br />
              with ease
            </h1>
          )}
          <div className={styles.hero3btn}>Sign Up</div>
        </div>
      </section>
      <Carousel
        responsive={responsive}
        autoPlay={true}
        infinite={true}
        showArrows={false}
        showStatus={false}
        autoPlaySpeed={10000}
        showDots={false}
        swipeable={true}
        arrows={false}
        pauseOnHover={false}
      >
        <section className={styles.hero32}>
          <div className={styles.hero3content2}>
            {width <= 600 ? (
              <h1>Discover.App is like TikTok & Twitch had a beautiful baby</h1>
            ) : (
              <h1>
                Discover.App is like
                <br />
                TikTok & Twitch had <br />a beautiful baby
              </h1>
            )}
            <div className={styles.hero3btn}>Sign Up</div>
          </div>
        </section>
        <section className={styles.hero32}>
          <div className={styles.hero3content2}>
            {width <= 600 ? (
              <h1>
                {" "}
                <br />
              </h1>
            ) : (
              <h1>
                TikTok for <br />
                gameplay videos <br />
                and app previews
              </h1>
            )}
            <div className={styles.hero3btn}>Sign Up</div>
          </div>
        </section>
      </Carousel>

      <section className={styles.hero4}>
        <div className={styles.hero4content}>
          <h1>
            Get paid <br />
            for performing
            <br />
            tasks
          </h1>
        </div>
      </section>

      <footer className={styles.footer}>
        <div className={styles.footercontent}>
          <h1>
            The first token powered video discovery <br />
            platform & community for everyone. <br />
            <span className={styles.yellow}>Join Us!</span>
          </h1>

          <div className={styles.input}>
            <input type="text" placeholder="Enter your email" />
            <div className={styles.footerbtn}>Sign Up</div>
          </div>
        </div>

        {width <= 600 ? (
          <nav className={styles.fnav}>
            <div className={styles.fnavleft}>
              <img className={styles.logo} src="logo.png" alt="logo" />

              <div className={styles.ftexts}>
                The first video AppStore for discovering apps, <br />
                games, contents & creators
                <br />
                <br />
                &copy; Discover.App 2022
              </div>

              <strong>Company</strong>
              <div className={styles.navlinks}>
                <a href="#">Privacy</a>
                <a href="#">Blog</a>
                <a href="#">Help Center</a>
                <a href="#">FAQ</a>
                <a href="#">Team</a>
                <a href="#">Terms of Service</a>
              </div>
            </div>
            <div className={styles.fnavright}>
              <img className={styles.icon} src="yt2.png" alt="logo" />
              <img className={styles.icon} src="tk2.png" alt="logo" />
              <img className={styles.icon} src="ig2.png" alt="logo" />
              <img className={styles.icon} src="tw2.png" alt="logo" />
            </div>
          </nav>
        ) : (
          <nav className={styles.fnav}>
            <div className={styles.fnavleft}>
              <img className={styles.logo} src="logo.png" alt="logo" />

              <div className={styles.navlinks}>
                <a href="#">
                  &copy; Discover.App 2022 / Terms of Use / Privacy Policy
                </a>
              </div>
            </div>
            <div className={styles.fnavright}>
              <img className={styles.icon} src="yt.png" alt="logo" />
              <img className={styles.icon} src="tk.png" alt="logo" />
              <img className={styles.icon} src="ig.png" alt="logo" />
              <img className={styles.icon} src="tw.png" alt="logo" />
            </div>
          </nav>
        )}
      </footer>

      <Modal
        show={showModal}
        onclose={() => {
          setShowModal(false);
        }}
        type={2}
      />
    </div>
  );
}
