import Head from "next/head";
import styles from "../styles/Creator.module.scss";

import Carousel from "react-multi-carousel";
import "react-multi-carousel/lib/styles.css";
import React, { useState, useEffect, useCallback } from "react";
import AOS from "aos";
import "aos/dist/aos.css";
import Nav from "../components/Nav";
import Modal from "../components/Modal";

export default function Creator() {
  const [showModal, setShowModal] = useState(false);
  const [width, setwidth] = useState("");

  const [scrollY, setScrollY] = useState(0);

  const onScroll = useCallback((event) => {
    const { pageYOffset, scrollY } = window;
    // console.log("yOffset", pageYOffset, "scrollY", scrollY);

    if (scrollY > 1100) {
      window.document.getElementById("scroll").scroll(scrollY - 1100, 0);
    }
    setScrollY(window.pageYOffset);
  }, []);

  useEffect(() => {
    //add eventlistener to window
    window.addEventListener("scroll", onScroll, { passive: true });
    // remove event on unmount to prevent a memory leak with the cleanup
    // return window.removeEventListener("scroll", onScroll, { passive: true });
  }, []);

  useEffect(() => {
    AOS.init({
      offset: 100,
    });

    if (typeof window !== "undefined") {
      let width_ =
        document.body.clientWidth ||
        window.innerHeight ||
        document.documentElement.clientHeigh;

      setwidth(width_);
    }
  }, []);

  const responsive = {
    superLargeDesktop: {
      breakpoint: { max: 4000, min: 3000 },
      items: 1,
    },
    desktop: {
      breakpoint: { max: 3000, min: 1024 },
      items: 1,
    },
    tablet: {
      breakpoint: { max: 1024, min: 464 },
      items: 1,
    },
    mobile: {
      breakpoint: { max: 464, min: 0 },
      items: 1,
    },
  };

  const data = [
    {
      id: 1,
      title: `Get paid for\n creating contents & \n ads for brands`,
      subtext: `Partner with brands to create specific contents and ads for their Discover.App 
      page. You will be handsomely rewarded! `,
    },
    {
      id: 1,
      title: `Introduce yourself 
      and your content to 
      potential followers`,
      subtext: `Post a 10 seconds video or showcase a snippet of your content to introduce yourself 
      to the Discover.App community. Capture their attention and redirect them to follow 
      you on Youtube, TikTok, Instagram and/or other social media channels`,
    },
  ];

  const scroll = [
    {
      id: 1,
      title: `Curate your \n
        own top 10 \n
        rankings & \n
        share with\n
        your friends`,
    },
    {
      id: 1,
      title: `Earn for \n
        completing\n
        tasks for\n
        brands`,
    },
    {
      id: 3,
      title: `Scroll\n
        through \n
        interactive\n
        gameplay`,
    },
    {
      id: 1,
      title: `Download\n
        apps & games\n
        directly in\n
        your feed`,
    },
  ];

  const CustomDot = ({ onClick, ...rest }) => {
    const {
      onMove,
      index,
      active,
      carouselState: { currentSlide, deviceType },
    } = rest;
    const carouselItems = [1, 2, 3];
    // onMove means if dragging or swiping in progress.
    // active is provided by this lib for checking if the item is active or not.
    return (
      <div
        className={active ? styles.active : styles.inactive}
        onClick={() => onClick()}
      />
    );
  };

  function getOffset(el) {
    const rect = el.getBoundingClientRect();
    return {
      left: rect.left + window.scrollX,
      top: rect.top + window.scrollY,
    };
  }

  return (
    <div
      onScroll={(e) => {
        console.log(e);
        console.log(document.body.scrollTop);
      }}
      className={styles.container}
    >
      <Head>
        <title>Discover</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Nav
          onPress={() => {
            setShowModal(true);
          }}
        />

        <Carousel
          responsive={responsive}
          autoPlay={true}
          infinite={true}
          showArrows={false}
          showStatus={false}
          autoPlaySpeed={10000}
          showDots={true}
          swipeable={true}
          arrows={false}
          pauseOnHover={false}
          // fade animation
          customTransition="fade"
          customDot={<CustomDot />}
        >
          <section className={styles.hero}>
            {width <= 600 ? (
              <div className={styles.herocontent}>
                <h1>Get paid for creating contents & ads for brands</h1>
                <p>
                  Partner with brands to create specific contents and ads for
                  their Discover.App page. You will be handsomely rewarded!
                </p>
                <div className={styles.herobtn}>Sign Up</div>
              </div>
            ) : (
              <div className={styles.herocontent}>
                <h1>
                  Get paid for
                  <br /> creating contents & <br /> ads for brands
                </h1>
                <p>
                  Partner with brands to create specific contents and ads for
                  their Discover.App
                  <br />
                  page. You will be handsomely rewarded!
                </p>
                <div className={styles.herobtn}>Sign Up</div>
              </div>
            )}
          </section>
          <section className={styles.hero}>
            {width <= 600 ? (
              <div className={styles.herocontent}>
                <h1>
                  Introduce yourself and your content to potential followers
                </h1>
                <p>
                  Post a 10 seconds video or showcase a snippet of your content
                  to introduce yourself to the Discover.App community. Capture
                  their attention and redirect them to follow you on Youtube,
                  TikTok, Instagram and/or other social media channels
                </p>
                <div className={styles.herobtn}>Sign Up</div>
              </div>
            ) : (
              <div className={styles.herocontent}>
                <h1>
                  Introduce yourself <br />
                  and your content to <br />
                  potential followers
                </h1>
                <p>
                  Post a 10 seconds video or showcase a snippet of your content
                  to introduce yourself <br />
                  to the Discover.App community. Capture their attention and
                  redirect them to follow <br />
                  you on Youtube, TikTok, Instagram and/or other social media
                  channels
                </p>
                <div className={styles.herobtn}>Sign Up</div>
              </div>
            )}
          </section>
        </Carousel>

        <div className={styles.hero2content}>
          <h1>Post & get discovered</h1>
          {width <= 600 ? (
            <p>
              Start to build your creator & influencer career by getting you and
              your content discovered serendipitously on Discover.App. You will
              stay on the front page of our audience minds with the right
              discovery video
            </p>
          ) : (
            <p>
              Start to build your creator & influencer career by getting you and
              your content discovered serendipitously <br />
              on Discover.App. You will stay on the front page of our audience
              minds with the right discovery video
            </p>
          )}
        </div>
      </main>

      <section className={styles.hero2}>
        {/* <marquee loop="10"> */}
        <div id="scroll" className={styles.scroll}>
          {[1, 2, 3, 4, 5].map((item, index) => {
            return (
              <div
                style={{
                  justifyContent: item % 2 == 0 ? "flex-end" : "flex-start",
                }}
                className={styles.scrollitemcon}
                key={index}
              >
                <img
                  src={`c${index + 1}.png`}
                  alt="pill"
                  className={styles.scrollitem}
                />
              </div>
            );
          })}
        </div>
        {/* </marquee> */}
      </section>

      <section className={styles.hero3}>
        <div className={styles.hero3content}>
          {width <= 600 ? (
            <h1>
              Increase your followers as you build your influence with
              Discover.App
            </h1>
          ) : (
            <h1>
              Increase your followers <br />
              as you build your influence <br />
              with Discover.App
            </h1>
          )}
          <div className={styles.hero3btn}>Sign Up</div>
        </div>
      </section>

      <section className={styles.hero32}>
        <div className={styles.hero3content2}>
          {width <= 600 ? (
            <h1>Go viral by creating ranking for app & games</h1>
          ) : (
            <h1>
              Go viral by creating
              <br />
              ranking for apps,
              <br />
              games & content
            </h1>
          )}
          <div className={styles.hero3btn}>Sign Up</div>
        </div>
      </section>

      <section className={styles.hero4}>
        <div className={styles.hero4content}>
          <h1>
            Partner with <br />
            brands to create <br />
            content
          </h1>
        </div>
      </section>

      <footer className={styles.footer}>
        <div className={styles.footercontent}>
          <h1>
            The first token powered video discovery <br />
            platform & community for everyone. <br />
            <span className={styles.yellow}>Join Us!</span>
          </h1>

          <div className={styles.input}>
            <input type="text" placeholder="Enter your email" />
            <div className={styles.footerbtn}>Sign Up</div>
          </div>
        </div>

        {width <= 600 ? (
          <nav className={styles.fnav}>
            <div className={styles.fnavleft}>
              <img className={styles.logo} src="logo.png" alt="logo" />

              <div className={styles.ftexts}>
                The first video AppStore for discovering apps, <br />
                games, contents & creators
                <br />
                <br />
                &copy; Discover.App 2022
              </div>

              <strong>Company</strong>
              <div className={styles.navlinks}>
                <a href="#">Privacy</a>
                <a href="#">Blog</a>
                <a href="#">Help Center</a>
                <a href="#">FAQ</a>
                <a href="#">Team</a>
                <a href="#">Terms of Service</a>
              </div>
            </div>
            <div className={styles.fnavright}>
              <img className={styles.icon} src="yt2.png" alt="logo" />
              <img className={styles.icon} src="tk2.png" alt="logo" />
              <img className={styles.icon} src="ig2.png" alt="logo" />
              <img className={styles.icon} src="tw2.png" alt="logo" />
            </div>
          </nav>
        ) : (
          <nav className={styles.fnav}>
            <div className={styles.fnavleft}>
              <img className={styles.logo} src="logo.png" alt="logo" />

              <div className={styles.navlinks}>
                <a href="#">
                  &copy; Discover.App 2022 / Terms of Use / Privacy Policy
                </a>
              </div>
            </div>
            <div className={styles.fnavright}>
              <img className={styles.icon} src="yt.png" alt="logo" />
              <img className={styles.icon} src="tk.png" alt="logo" />
              <img className={styles.icon} src="ig.png" alt="logo" />
              <img className={styles.icon} src="tw.png" alt="logo" />
            </div>
          </nav>
        )}
      </footer>

      <Modal
        show={showModal}
        onclose={() => {
          setShowModal(false);
        }}
        type={3}
      />
    </div>
  );
}
