import Head from "next/head";
import styles from "../styles/Main.module.scss";

import Carousel from "react-multi-carousel";
import "react-multi-carousel/lib/styles.css";
import React, { useState, useEffect } from "react";
import AOS from "aos";
import "aos/dist/aos.css";
import Nav from "../components/Nav";
import Modal from "../components/Modal";
import Link from "next/link";
import Footer from "../components/Footer";

export default function Creator() {
  const [showModal, setShowModal] = useState(false);
  const [showModal2, setShowModal2] = useState(false);
  const [showModal3, setShowModal3] = useState(false);

  const [width, setwidth] = useState("");

  useEffect(() => {
    AOS.init({
      offset: 100,
    });

    if (typeof window !== "undefined") {
      let width_ =
        document.body.clientWidth ||
        window.innerHeight ||
        document.documentElement.clientHeigh;

      setwidth(width_);
    }

    setInterval(() => {
      AOS.refresh();
    }, 3000);
  }, []);

  const responsive = {
    superLargeDesktop: {
      breakpoint: { max: 4000, min: 3000 },
      items: 1,
    },
    desktop: {
      breakpoint: { max: 3000, min: 1024 },
      items: 1,
    },
    tablet: {
      breakpoint: { max: 1024, min: 464 },
      items: 1,
    },
    mobile: {
      breakpoint: { max: 464, min: 0 },
      items: 1,
    },
  };

  const data = [
    {
      id: 1,
      title: `Get paid for\n creating contents & \n ads for brands`,
      subtext: `Partner with brands to create specific contents and ads for their Discover.App 
      page. You will be handsomely rewarded! `,
    },
    {
      id: 1,
      title: `Introduce yourself 
      and your content to 
      potential followers`,
      subtext: `Post a 10 seconds video or showcase a snippet of your content to introduce yourself 
      to the Discover.App community. Capture their attention and redirect them to follow 
      you on Youtube, TikTok, Instagram and/or other social media channels`,
    },
  ];

  const scroll = [
    {
      id: 1,
      title: `Curate your \n
        own top 10 \n
        rankings & \n
        share with\n
        your friends`,
    },
    {
      id: 1,
      title: `Earn for \n
        completing\n
        tasks for\n
        brands`,
    },
    {
      id: 3,
      title: `Scroll\n
        through \n
        interactive\n
        gameplay`,
    },
    {
      id: 1,
      title: `Download\n
        apps & games\n
        directly in\n
        your feed`,
    },
  ];

  return (
    <div className={styles.container}>
      <Head>
        <title>Discover</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className={styles.main}>
        <Nav
          onPress={() => {
            setShowModal(true);
          }}
        />

        <Carousel
          responsive={responsive}
          autoPlay={false}
          infinite={true}
          showArrows={false}
          showStatus={false}
          autoPlaySpeed={100000}
          showDots={false}
          swipeable={true}
          arrows={false}
          pauseOnHover={false}
        >
          <section className={styles.hero}>
            <div className={styles.herocontent}>
              <div className={styles.heroimgs}>
                <img
                  data-aos="fade-down"
                  data-aos-delay="100"
                  src="/wombo.png"
                  alt="icon"
                  data-aos-mirror="false"
                />
                <img
                  data-aos="fade-down"
                  data-aos-delay="200"
                  src="/app1.png"
                  alt="icon"
                />
                <img
                  data-aos="fade-down"
                  data-aos-delay="300"
                  src="/amongus.png"
                  alt="icon"
                />
                <img
                  data-aos="fade-down"
                  data-aos-delay="400"
                  src="/hulu.png"
                  alt="icon"
                />
                <img
                  data-aos="fade-down"
                  data-aos-delay="500"
                  src="/app2.png"
                  alt="icon"
                />
                <img
                  data-aos="fade-down"
                  data-aos-delay="600"
                  src="/app3.png"
                  alt="icon"
                />
              </div>
              <h1>
                The power of communities <br />
                in discovering apps, content & <br />
                creators
              </h1>
              {width <= 600 ? (
                <p>
                  Discover.App provides our users a token powered video platform
                  for discovering apps, dapps, games, content, creators, web3
                  community, crypto projects, tokens and everything in between
                </p>
              ) : (
                <p>
                  Discover.App provides our users a token powered video platform
                  for discovering apps, dapps, games, <br />
                  content, creators, web3 community, crypto projects, tokens and
                  everything in between
                  <br />
                </p>
              )}
              {/* <div className={styles.herobtn}>Sign Up</div> */}
            </div>
          </section>
        </Carousel>
      </section>

      <section className={styles.hero3}>
        <img src="/h3.png" alt="hero3" />
        <div className={styles.hero3content}>
          <p>Are you a developer or publisher?</p>
          <h1>
            Promote your <br />
            App, Dapps & <br />
            Games
          </h1>
          <div className={styles.btnrow}>
            <div
              onClick={() => {
                setShowModal(true);
              }}
              className={styles.hero3btn}
            >
              Sign Up
            </div>
            <Link href="/developers">
              <div className={styles.hero3btno}>Learn more</div>
            </Link>
          </div>
        </div>
      </section>

      <section className={styles.hero32}>
        <div className={styles.hero3content2}>
          <p>Are you a Consumer or Superfan?</p>
          {width <= 600 ? (
            <h1>
              Discover, share <br />& promote new apps, content and get paid!
            </h1>
          ) : (
            <h1>
              Discover, share <br />& promote new <br />
              apps and content <br />
              And get paid!
            </h1>
          )}
          <div className={styles.btnrow}>
            <div
              onClick={() => {
                setShowModal2(true);
              }}
              className={styles.hero3btn}
            >
              Get Early Access
            </div>
            <Link href="/consumer">
              <div className={styles.hero3btno}>Learn more</div>
            </Link>
          </div>
        </div>
        <img src="/h32.png" alt="hero3" />
      </section>

      <section className={styles.hero3}>
        <img src="/h3.png" alt="hero3" />
        <div className={styles.hero3content}>
          <p>Are you a Creator, Influencer or Celebrity?</p>
          {width <= 600 ? (
            <h1>
              Market yourself and your content to the Discover.App community
            </h1>
          ) : (
            <h1>
              Market yourself <br />
              and your content <br />
              to the Discover.App
              <br />
              community
            </h1>
          )}
          <div className={styles.btnrow}>
            <div
              onClick={() => {
                setShowModal3(true);
              }}
              className={styles.hero3btn}
            >
              Get Early Access
            </div>
            <Link href="/creators">
              <div className={styles.hero3btno}>Learn more</div>
            </Link>
          </div>
        </div>
      </section>

      <Footer />

      <Modal
        show={showModal}
        onclose={() => {
          setShowModal(false);
        }}
        type={1}
      />
      <Modal
        show={showModal2}
        onclose={() => {
          setShowModal2(false);
        }}
        type={2}
      />
      <Modal
        show={showModal3}
        onclose={() => {
          setShowModal3(false);
        }}
        type={3}
      />
    </div>
  );
}
